### ISSUE TITLE
Error while running the generator

### ISSUE THREAD

**Issue by lfuelling** [micromata/generator-bootstrap-kickstart#23]
I get this error when running `yo bootstrap-kickstart`. I've already tried to update (even with --force) but I can't get it to work. I also installed `lodash` manually.

```bash
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-bootstrap-kickstart/node_modules/yeoman-generator/node_modules/yeoman-environment/lib/environment.js:6:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

```

I don't know if this is an error in the generator or an yeoman error. Any help is appreciated.

**Comment by mischah** [comment]
mhmm. Which version of yeoman are you using? 

    yo --version

And which version of our generator?

And what are the steps to reproduce that?

**Comment by mischah** [comment]
Closing this one.

@lfuelling Feel free to comment if you still encounter problems.
